name: CD - Deploy to Elastic Beanstalk

on:
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout merged code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build --if-present

    - name: Zip application
      run: zip -r app.zip . -x "*.git*"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: demo-account-activity-monitor
        environment_name: Demo-account-activity-monitor-env-1
        region: us-east-1
        version_label: github-${{ github.run_id }}
        deployment_package: app.zip
        use_existing_version_if_available: true
